import { inMemoryStore } from "../repository/inMemoryStore.js";

const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

export const getAnalytics = (req, res) => {
  const history = inMemoryStore.getAnalyticsHistory();
  const latest = history[history.length - 1] || {
    latency: 18,
    throughputMbps: 742,
    packetsPerSec: 1450,
    overheadPercent: 5.2,
    securityScore: 94
  };

  res.json({
    success: true,
    data: {
      metricsHistory: history,
      summary: {
        currentLatencyMs: latest.latency,
        currentThroughputMbps: latest.throughputMbps,
        packetsProcessedSec: latest.packetsPerSec,
        overheadPercent: latest.overheadPercent,
        securityScore: latest.securityScore,
        performanceScore: Math.floor(
          Math.min(100, Math.max(50, 100 - (latest.latency * 0.4) - (latest.overheadPercent * 2) + (latest.securityScore * 0.2)))
        )
      }
    }
  });
};

export const getComparisonData = (req, res) => {
  const history = inMemoryStore.getAnalyticsHistory();
  const latest = history[history.length - 1] || {};

  res.json({
    success: true,
    data: {
      metrics: {
        latency: { before: 12, after: latest.latency || 18, unit: "ms" },
        throughput: { before: 800, after: latest.throughputMbps || 742, unit: "Mbps" },
        packetSizeAvg: { before: 1024, after: 1077, unit: "bytes" },
        overhead: { before: 0, after: latest.overheadPercent || 5.2, unit: "%" },
        processingTime: { before: 0.2, after: 1.4, unit: "ms" },
        fingerprintVisibility: { before: "100% (Raw Cleartext Protocol)", after: "6% (Homogenous TLS Stream)", unit: "Visibility Score" }
      },
      performanceScore: 92
    }
  });
};

export const getPrivacyAnalytics = (req, res) => {
  const history = inMemoryStore.getAnalyticsHistory();
  const latest = history[history.length - 1] || { latency: 18, overheadPercent: 5.2, securityScore: 94 };
  const privacyImprovement = clamp(100 - (latest.overheadPercent * 8) - (latest.latency / 2), 25, 94);

  res.json({
    success: true,
    data: {
      beforeMorphing: {
        fingerprintVisibility: "HIGH",
        packetSizeSimilarity: "HIGH",
        timingSimilarity: "HIGH",
        burstSimilarity: "HIGH"
      },
      afterMorphing: {
        fingerprintVisibility: "LOW",
        packetSizeSimilarity: "LOW",
        timingSimilarity: "MEDIUM",
        burstSimilarity: "LOW"
      },
      privacyImprovementPercent: Number(privacyImprovement.toFixed(1)),
      disclaimer: "Simulation/demo metric only; it is not a real-world guarantee of anonymity.",
      currentScore: latest.securityScore,
      metrics: {
        packetSizeSimilarity: 32,
        timingSimilarity: 48,
        burstSimilarity: 31,
        trafficDistributionSimilarity: 29
      }
    }
  });
};

export const getSecurityAnalytics = (req, res) => {
  const events = inMemoryStore.getSecurityEvents();
  res.json({
    success: true,
    data: {
      activeSessions: inMemoryStore.getSessions().length,
      suspiciousEvents: events.filter((event) => ["MEDIUM", "HIGH"].includes(event.severity)).length,
      morphingOperations: events.filter((event) => event.action === "PADDING_SHAPED").length,
      encryptionOperations: events.filter((event) => event.action === "KEY_ROTATED").length,
      sessionAnomalies: 2,
      profileChanges: 3,
      events: events.slice(0, 10)
    }
  });
};

export const getQoSAnalytics = (req, res) => {
  const history = inMemoryStore.getAnalyticsHistory();
  const latest = history[history.length - 1] || { latency: 18, throughputMbps: 742, packetsPerSec: 1450, overheadPercent: 5.2 };

  res.json({
    success: true,
    data: {
      before: {
        latencyMs: 42,
        jitterMs: 4,
        packetLossPercent: 1.2,
        throughputMbps: 12.4,
        packetsPerSecond: 900
      },
      after: {
        latencyMs: latest.latency || 18,
        jitterMs: latest.jitterMs || 2,
        packetLossPercent: 0.9,
        throughputMbps: latest.throughputMbps / 60,
        packetsPerSecond: latest.packetsPerSec
      },
      disclaimer: "QoS values are generated by the NetMorph simulation engine for demo purposes only."
    }
  });
};
