import AIProvider from "./aiProvider.js";

class GeminiAIProvider extends AIProvider {
  get apiKey() {
    return process.env.AI_API_KEY;
  }

  get model() {
    return process.env.AI_MODEL || "gemini-1.5-flash";
  }

  get apiUrl() {
    return `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent`;
  }

  async analyzeNetworkMetrics(data) {
    if (!this.apiKey) {
      throw new Error("AI_API_KEY is not configured.");
    }

    const prompt = this.buildPrompt(data);

    try {
      // Setup timeout controller
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000); // 15s timeout

      const response = await fetch(`${this.apiUrl}?key=${this.apiKey}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }]
            }
          ],
          generationConfig: {
            temperature: 0.2,
            responseMimeType: "application/json"
          }
        }),
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`AI API Error (${response.status}): ${errorText}`);
      }

      const responseData = await response.json();

      if (!responseData.candidates || responseData.candidates.length === 0) {
        throw new Error("No response generated by AI.");
      }

      const textResponse = responseData.candidates[0].content.parts[0].text;
      
      // The API is configured to return JSON, but we parse it carefully
      const parsedJson = JSON.parse(textResponse);
      
      return this.validateAndFormatResponse(parsedJson);
    } catch (error) {
      console.error("[AI Service Error]", error.message);
      if (error.name === "AbortError") {
        throw new Error("AI API request timed out.");
      }
      throw new Error(`Failed to analyze network with AI: ${error.message}`);
    }
  }

  buildPrompt(data) {
    return `
You are an expert Network Security & Traffic Optimization Assistant for a 5G-native traffic morphing platform.
Analyze the following real-time network, traffic, and security metrics, and provide intelligent recommendations.

INPUT DATA (JSON):
${JSON.stringify(data, null, 2)}

REQUIREMENTS:
1. Identify any potential network bottlenecks, QoS issues, or security concerns.
2. Suggest actionable recommendations to optimize performance or improve security.
3. Return the analysis STRICTLY as a JSON object matching the exact schema below.

EXPECTED JSON SCHEMA:
{
  "riskLevel": "LOW | MEDIUM | HIGH | CRITICAL",
  "networkCondition": "string (brief summary of overall condition)",
  "analysis": "string (detailed explanation of the analysis)",
  "recommendations": [
    {
      "action": "string (what to do)",
      "reason": "string (why to do it)",
      "priority": "LOW | MEDIUM | HIGH",
      "expectedImpact": "string (expected result)"
    }
  ],
  "securityConcerns": [
    "string (list of potential security risks, empty array if none)"
  ],
  "qosRecommendation": {
    "priority": "string (suggested QoS priority class)",
    "reason": "string (why this priority is needed)"
  }
}

Do not include any text outside the JSON object.
`;
  }

  validateAndFormatResponse(parsedJson) {
    // Basic validation to ensure all expected fields exist with fallback defaults
    return {
      riskLevel: parsedJson.riskLevel || "UNKNOWN",
      networkCondition: parsedJson.networkCondition || "Analysis unavailable",
      analysis: parsedJson.analysis || "No detailed analysis provided.",
      recommendations: Array.isArray(parsedJson.recommendations) ? parsedJson.recommendations : [],
      securityConcerns: Array.isArray(parsedJson.securityConcerns) ? parsedJson.securityConcerns : [],
      qosRecommendation: parsedJson.qosRecommendation || { priority: "DEFAULT", reason: "N/A" }
    };
  }
}

// Export a singleton instance. 
// Can easily be swapped to OpenAIProvider or others in the future based on ENV vars.
const aiService = new GeminiAIProvider();
export default aiService;
